project:
  type: book
  output-dir: docs
book:
  title: "映画の興行収入と制作費・投票数・評価点の関連"
  subtitle: "ジャンル・公開時期の違いと極端値の影響"
  author: "Suzuki Ayana"
  date: "2026-09-29"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd
    - chapter8.qmd
  appendices:
    - guide.qmd
format:
  html:
    embed-resources: false
    toc: true
    toc-depth: 2
    theme: default
    lang: ja
    code-copy: true
execute:
  enabled: false
